### ISSUE TITLE
Algorithm style nits

### ISSUE THREAD

**Issue by domenic** [ricea/encoding-streams#3]
For associated "internal slots" (decoder, stream, ignore BOM flag, BOM seen flag, and error mode), their defining instance should be a `<dfn>`, and all subsequent uses of or references to them should be `<a>`s. Currently both are `<b>`. (The existing spec seems bad at this.)

The "decode and enqueue a chunk" and "flush and enque" algorithms should take a transformer object as an argument _transformer_, and then they can refer to the "internal slots" as e.g. _transformer_'s decoder.

We'll probably want special phrases for doing things like constructing a TransformStream and calling the controller methods, similar to https://fetch.spec.whatwg.org/#readablestream. However I still think I should move those into the stream spec: https://github.com/whatwg/streams/issues/372#issuecomment-237456743. For now the style you used is fine.

**Comment by ricea** [comment]
I kept the "internal slots" bold because otherwise there's no way to visually distinguish between the slot named "stream" and the concept named "stream".

Yeah, I probably should have just renamed the slot. There's only so many things you can have named "stream".

**Comment by domenic** [comment]
I think it's OK to have overlap between a "type name" and a "property name" in the same document, even without bold distinguishers. But yeah, this is all kind of on the Encoding spec to get fixed there first; I filed https://github.com/whatwg/encoding/issues/76 in case you didn't see.

**Comment by ricea** [comment]
I'm not sure I'm using the right language to "call" the algorithm. Could you take a look?

**Comment by domenic** [comment]
Are you referring to

> Set transformer["transform"] to a function which takes chunk, controller arguments and runs the decode and enqueue a chunk algorithm on the transformer object. 

? If so, that looks great to me.

**Comment by ricea** [comment]
Yes, I was. Thank you for checking that.
