### ISSUE TITLE
"transform" as a concept does not have attributes; it has property

### ISSUE THREAD

**Issue by domenic** [ricea/encoding-streams#5]
It's not entirely clear that the "transform" concept holds a JavaScript TransformStream object. Making that clearer would help.

Then,

> The readable attribute’s getter must return the readable attribute of transform. 

and its friend should probably be revised. I'm not sure whether to just do a small revision, like s/attribute/property, or something more extensive, like

> The readable attribute's getter must return the value of the readable property of the transform object, i.e. the value returned by Get(transform, "readable"). NOTE: since the transform object is unobservable, this value can be cached.

**Comment by ricea** [comment]
In hindsight I think talking about **transform** as if it was a Javascript object was a mistake. I've changed the language to talk about its slots to avoid any implication that we might be touching Javascript here.

I'm now using wording like:

> The `readable` attribute’s getter must return the contents of transform’s [[readable]] internal slot.

I'm not sure about whether it makes sense to talk about "the contents of" a slot. Let me know what you think.

**Comment by domenic** [comment]
Looks great! I think transform.[[readable]] would also work, but it can be a bit weird mixing apostrophe-style properties ("dec's transform") with dot-style ("transform.[[readable]]"), so the current thing is good too.
