### ISSUE TITLE
"is locked" should be more precise

### ISSUE THREAD

**Issue by domenic** [ricea/encoding-streams#6]
In particular it should probably use https://streams.spec.whatwg.org/#is-readable-stream-locked and https://streams.spec.whatwg.org/#is-writable-stream-locked. Plus we have the imprecision in how you refer to the readable and writable properties as noted in #5.

Maybe we need to define centrally the concepts of a TextDecoder's readable and a TextDecoder's writable.

**Comment by ricea** [comment]
I was trying to minimise the use of abstract operations to match the style of the rest of the spec, but it didn't work out.

Ultimately we will probably need some abstractions defined in the WebIDL standard to permit prose-y standards to talk about streams without talking about abstract operations. But I hope this encoding standard work won't block on that.
